// Lista de URLs das imagens
const listaDeImagens = [
    'pal_images/anubis-image.png',
    'pal_images/arsox-image.png',
    'pal_images/anubis-image.png',
    'pal_images/arsox-image.png',
    'pal_images/astegon-image.png',
    'pal_images/azurobe-image.png',
    'pal_images/beakon-image.png',
    'pal_images/beegarde-image.png',
    'pal_images/blazamut-image.png',
    'pal_images/blazehowl-image.png',
    'pal_images/blazehowl-noct-image.png',
    'pal_images/bristla-image.png',
    'pal_images/broncherry-aqua-image.png',
    'pal_images/broncherry-image.png',
    'pal_images/bushi-image.png',
    'pal_images/caprity-image.png',
    'pal_images/cattiva-image.png',
    'pal_images/cawgnito-image.png',
    'pal_images/celaray-image.png',
    'pal_images/chikipi-image.png',
    'pal_images/chillet-image.png',
    'pal_images/cinnamoth-image.png',
    'pal_images/cremis-image.png',
    'pal_images/cryolinx-image.png',
    'pal_images/daedream-image.png',
    'pal_images/dazzi-image.png',
    'pal_images/depresso-image.png',
    'pal_images/digtoise-image.png',
    'pal_images/dinossom-image.png',
    'pal_images/dinossom-lux-image.png',
    'pal_images/direhowl-image.png',
    'pal_images/dumud-image.png',
    'pal_images/eikthyrdeer-image.png',
    'pal_images/eikthyrdeer-terra-image.png',
    'pal_images/elizabee-image.png',
    'pal_images/elphidran-image.png',
    'pal_images/faleris-image.png',
    'pal_images/felbat-image.png',
    'pal_images/fenglope-image.png',
    'pal_images/flambelle-image.png',
    'pal_images/flopie-image.png',
    'pal_images/foxcicle-image.png',
    'pal_images/foxparks-image.png',
    'pal_images/frostallion-image.png',
    'pal_images/fuack-image.png',
    'pal_images/fuddler-image.png',
    'pal_images/galeclaw-image.png',
    'pal_images/gobfin-ignis-image.png',
    'pal_images/gobfin-image.png',
    'pal_images/gorirat-image.png',
    'pal_images/grintale-image.png',
    'pal_images/grizzbolt-image.png',
    'pal_images/gumoss-image.png',
    'pal_images/hangyu-cryst-image.png',
    'pal_images/hangyu-image.png',
    'pal_images/helzephyr-image.png',
    'pal_images/hoocrates-image.png',
    'pal_images/ice-kingpaca-image.png',
    'pal_images/ice-reptyro-image.png',
    'pal_images/incineram-image.png',
    'pal_images/incineram-noct-image.png',
    'pal_images/jetragon-image.png',
    'pal_images/jolthog-cryst-image.png',
    'pal_images/jolthog-image.png',
    'pal_images/jormuntide-ignis-image.png',
    'pal_images/jormuntide-image.png',
    'pal_images/katress-image.png',
    'pal_images/kelpsea-ignis-image.png',
    'pal_images/kelpsea-image.png',
    'pal_images/killamari-image.png',
    'pal_images/kingpaca-image.png',
    'pal_images/kitsun-image.png',
    'pal_images/lamball-image.png',
    'pal_images/leezpunk-ignis-image.png',
    'pal_images/leezpunk-image.png',
    'pal_images/lifmunk-image.png',
    'pal_images/loupmoon-image.png',
    'pal_images/lovander-image.png',
    'pal_images/lunaris-image.png',
    'pal_images/lyleen-image.png',
    'pal_images/mammorest-cryst-image.png',
    'pal_images/mammorest-image.png',
    'pal_images/maraith-image.png',
    'pal_images/mau-cryst-image.png',
    'pal_images/mau-image.png',
    'pal_images/menasting-image.png',
    'pal_images/mossanda-image.png',
    'pal_images/mossanda-lux-image.png',
    'pal_images/mozzarina-image.png',
    'pal_images/necromus-image.png',
    'pal_images/nitewing-image.png',
    'pal_images/nox-image.png',
    'pal_images/orserk-image.png',
    'pal_images/paladius-image.png',
    'pal_images/pengullet-image.png',
    'pal_images/penking-image.png',
    'pal_images/petallia-image.png',
    'pal_images/pyrin-image.png',
    'pal_images/pyrin-noct-image.png',
    'pal_images/quivern-image.png',
    'pal_images/ragnahawk-image.png',
    'pal_images/rayhound-image.png',
    'pal_images/reindrix-image.png',
    'pal_images/relaxaurus-image.png',
    'pal_images/relaxsaurus-lux-image.png',
    'pal_images/reptyro-image.png',
    'pal_images/ribbuny-image.png',
    'pal_images/robinquill-image.png',
    'pal_images/robinquill-terra-image.png',
    'pal_images/rooby-image.png',
    'pal_images/rushoar-image.png',
    'pal_images/shadowbeak-image.png',
    'pal_images/sibelyx-image.png',
    'pal_images/sparkit-image.png',
    'pal_images/surfent-image.png',
    'pal_images/surfent-lux-image.png',
    'pal_images/suzaku-aqua-image.png',
    'pal_images/suzaku-image.png',
    'pal_images/swee-image.png',
    'pal_images/sweepa-image.png',
    'pal_images/tanzee-image.png',
    'pal_images/teafant-image.png',
    'pal_images/tocotoco-image.png',
    'pal_images/tombat-image.png',
    'pal_images/undefined-image.png',
    'pal_images/univolt-image.png',
    'pal_images/vaelet-image.png',
    'pal_images/vanwyrm-cryst-image.png',
    'pal_images/vanwyrm-image.png',
    'pal_images/verdash-image.png',
    'pal_images/vixy-image.png',
    'pal_images/warsect-image.png',
    'pal_images/wixen-image.png',
    'pal_images/woolipop-image.png',
    'pal_images/wumpo-botan-image.png',
    'pal_images/wumpo-image.png',
    // Adicione mais URLs conforme necessário
  ];
  
  // Função para escolher aleatoriamente uma imagem da lista
  function escolherImagemAleatoria() {
    const indiceAleatorio = Math.floor(Math.random() * listaDeImagens.length);
    const imagemEscolhida = listaDeImagens[indiceAleatorio];
    return imagemEscolhida;
  }
  
  // Exemplo de como usar a imagem aleatória ao carregar a página
  document.addEventListener('DOMContentLoaded', function () {
    const imagemAleatoria = escolherImagemAleatoria();
    const imagemElement = document.getElementById('suaImagem'); // Substitua 'suaImagem' pelo ID do elemento de imagem em seu HTML
    imagemElement.src = imagemAleatoria;
  });